"""create transaction table

Revision ID: 5bc76e47bee0
Revises: f35dd21fcd4c
Create Date: 2025-12-24 18:47:44.162828

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel
from sqlalchemy.dialects import oracle

# revision identifiers, used by Alembic.
revision: str = '5bc76e47bee0'
down_revision: Union[str, Sequence[str], None] = 'f35dd21fcd4c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('transaction',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('amount', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('account_id', sa.Integer(), nullable=False),
    sa.Column('transaction_type', sa.Enum('DEPOSIT', 'WITHDRAW', 'TRANSFER', name='transactiontype'), nullable=False),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True),
    sa.Column('data', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['account_id'], ['account.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.alter_column('account', 'id',
               existing_type=oracle.NUMBER(asdecimal=False),
               server_default=None,
               existing_nullable=False,
               autoincrement=True)
    op.alter_column('account', 'number',
               existing_type=sa.VARCHAR(length=20),
               nullable=True)
    op.drop_index(op.f('uq_account_number'), table_name='account')
    op.create_index(op.f('ix_account_number'), 'account', ['number'], unique=True)
    op.alter_column('user', 'id',
               existing_type=oracle.NUMBER(asdecimal=False),
               server_default=None,
               existing_nullable=False,
               autoincrement=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user', 'id',
               existing_type=oracle.NUMBER(asdecimal=False),
               server_default=sa.Identity(always=True, on_null=False, start=1, increment=1, minvalue=1, maxvalue=9999999999999999999999999999, cycle=False, cache=20, order=False),
               existing_nullable=False,
               autoincrement=True)
    op.drop_index(op.f('ix_account_number'), table_name='account')
    op.create_index(op.f('uq_account_number'), 'account', ['number'], unique=True)
    op.alter_column('account', 'number',
               existing_type=sa.VARCHAR(length=20),
               nullable=False)
    op.alter_column('account', 'id',
               existing_type=oracle.NUMBER(asdecimal=False),
               server_default=sa.Identity(always=False, on_null=True, start=1, increment=1, minvalue=1, maxvalue=9999999999999999999999999999, cycle=False, cache=20, order=False),
               existing_nullable=False,
               autoincrement=True)
    op.drop_table('transaction')
    # ### end Alembic commands ###
