"""create account table

Revision ID: f35dd21fcd4c
Revises: da23be911e82
Create Date: 2025-12-23 11:41:46.409025

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel
from sqlalchemy.dialects import oracle

# revision identifiers, used by Alembic.
revision: str = 'f35dd21fcd4c'
down_revision: Union[str, Sequence[str], None] = 'da23be911e82'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('account',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('number', sqlmodel.sql.sqltypes.AutoString(length=20), nullable=True),
    sa.Column('balance', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_account_number'), 'account', ['number'], unique=True)
    # op.alter_column('user', 'id',
    #            existing_type=oracle.NUMBER(asdecimal=False),
    #            server_default=None,
    #            existing_nullable=False,
    #            autoincrement=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user', 'id',
               existing_type=oracle.NUMBER(asdecimal=False),
               server_default=sa.Identity(always=True, on_null=False, start=1, increment=1, minvalue=1, maxvalue=9999999999999999999999999999, cycle=False, cache=20, order=False),
               existing_nullable=False,
               autoincrement=True)
    op.drop_index(op.f('ix_account_number'), table_name='account')
    op.drop_table('account')
    # ### end Alembic commands ###
